stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker build -t flask_app_image .

test-job:
  stage: test
  script:
    - docker run --rm flask_app_image -m unittest -s -v

deploy-job:
  stage: deploy
  script:
    - docker compose up -d