version: '3'

services:
  web:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
    ports:
      - "4000:5000"
    restart: "no"
  db:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
