global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: 'node'
    static_configs:
      - targets: [ 'node_exporter:9100' ]

  - job_name: 'flask_app'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'web:5000']
