name: App deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t flask-test-app .

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: docker run --rm flask-test-app unittest

#  deploy:
#    runs-on: ubuntu-latest
#    needs: [ build, test ]
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Deploy to server via SSH
#        uses: appleboy/ssh-agent@v0.9.0
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          script: |
#            mkdir cloud
#            cd /cloud
#            docker-compose down
#            docker-compose up -d
