name: App deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t "${{ secrets.DOCKER_USERNAME }}/flask-app" .
          docker push "${{ secrets.DOCKER_USERNAME }}/flask-app:latest"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Image for Testing
        run: |
          docker pull "${{ secrets.DOCKER_USERNAME }}/flask-app:latest"

      - name: Run Tests in Docker Container
        run: |
          docker run --rm \
#            -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
#            -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
#            -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
#            -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
#            -e REDIS_HOST=${{ secrets.REDIS_HOST }} \
#            -e REDIS_PORT=${{ secrets.REDIS_PORT }} \
            "${{ secrets.DOCKER_USERNAME }}/flask-app:latest" \
            unittest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd fullstack-cloud-deploy
            docker-compose pull web
            git pull
            docker-compose up -d --build web
